# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Issue Notify Telegram
        # You may pin to the exact commit or the version.
        # uses: naiw1023/notify-telegram@7b7f913ce885f49504984ebff84e2f90ab9aa75f
        uses: naiw1023/notify-telegram@v0.0.5
        with:
          # Chat to send: chat id or @channel_name
          chat: ${{ secrets.TELEGRAM_TO }}
          # Telegram Bot token
          token: ${{ secrets.TELEGRAM_TOKEN }}
          # Job status
          status: Online
          # Custom message
          message: Nuevo contenido en https://github.com/DarkWolf3011/EvoSwarm-Variations 

          
